name: Cache Google Sheets Data

on:
  schedule:
    # Run this workflow every minute
    - cron: '* * * * *'

jobs:
  cache-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from Google Sheets API
      run: |
        curl -o data.json 'https://opensheet.elk.sh/1ibbywsC1tQ_sLPX8bUAjC-vrTrUqZgZA46W_sxWw4Ss/Approved+Datasheets+(Monitor)'

    - name: Commit and push if changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add data.json
        git commit -m "Update cached data" -a || echo "No changes to commit"
        git push
