name: Cache Google Sheets Data

on:
  schedule:
    # Run this workflow every hour (you can adjust the frequency as needed)
    - cron: '0 */3 * * *'

jobs:
  cache-data:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch API
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://opensheet.elk.sh/1ibbywsC1tQ_sLPX8bUAjC-vrTrUqZgZA46W_sxWw4Ss/Approved+Datasheets+(Monitor)'
        file: 'data.json'
